spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/intershop
    username: root
    password: root
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    ru.rpovetkin: DEBUG
    org.springframework.web: TRACE
    org.springframework.http.codec: DEBUG
#    reactor.netty: DEBUG