# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.21-alpine3.22
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=intershop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  # Redis сервис для кеширования
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  online-store-app:
    build:
      context: .
      dockerfile: online-store/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=intershop
      - DB_USER=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  payment-service-app:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8081:8080"

volumes:
  redis_data: