spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/intershop
    username: intershop1
    password: admin123
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    ru.rpovetkin: DEBUG
    org.springframework.web: TRACE
    org.springframework.http.codec: DEBUG
#    reactor.netty: DEBUG