# FROM amazoncorretto:21-alpine-jdk
# COPY target/*.jar app.jar
# ENTRYPOINT ["java","-jar","/app.jar"]

# # Build stage
# FROM maven:3.9.6-amazoncorretto-21 AS build
# WORKDIR /workspace
# COPY pom.xml .
# COPY src src
# RUN mvn clean package

# Run stage
FROM amazoncorretto:21-alpine
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

# # Run stage
#   FROM amazoncorretto:21-alpine
#   WORKDIR /app
#   COPY target/*.jar app.jar
#   EXPOSE 8081
#   ENTRYPOINT ["java", "-jar", "app.jar"]