openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
servers:
- url: http://payment-service-app:8080
paths:
  /payment:
    get:
      parameters:
      - explode: true
        in: query
        name: amountForPay
        required: true
        schema:
          format: double
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Достаточно ли средств
      summary: "Проверить, хватает ли средств для оплаты"
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_payment_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Успешно оплачено или нет
      summary: Провести оплату
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    _payment_post_request:
      properties:
        amountForPay:
          format: double
          type: number
      type: object
