# Build stage
# FROM maven:3.9.6-amazoncorretto-21 AS build
# WORKDIR /workspace
# # Copy parent POM first
# COPY ../pom.xml ./pom.xml
# # Then copy module POM and source
# COPY pom.xml ./payment-service/pom.xml
# COPY src ./payment-service/src
# RUN mvn clean package

# # FROM amazoncorretto:21-alpine-jdk
  # COPY target/*.jar app.jar
  # ENTRYPOINT ["java","-jar","/app.jar"]

# Run stage
FROM amazoncorretto:21-alpine
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]